#!/usr/bin/env python3
from __future__ import annotations
import json, re, sys
from pathlib import Path

def slug_from_filename(path: Path) -> str:
    name = path.stem
    for prefix in ["resume-", "resume-enhancement-", "bullet-ranking-", "resume-tailoring-"]:
        if name.startswith(prefix): name = name[len(prefix):]
    for suffix in ["-assembled-v2", "-assembled-v3", "-v1", "-v2", "-teal-v1"]:
        if name.endswith(suffix): name = name[:-len(suffix)]
    return name

def find_by_slug(folder: Path, prefix: str, slug: str, ext: str = ".json") -> Path | None:
    direct = folder / f"{prefix}{slug}{ext}"
    if direct.exists(): return direct
    st = set(slug.split("-"))
    best, score = None, 0
    for p in folder.glob(f"*{ext}"):
        pt = set(slug_from_filename(p).split("-"))
        s = len(st & pt)
        if s > score:
            best, score = p, s
    return best if score >= 2 else None

def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))

def extract_contact_block(text: str) -> str:
    out = []
    for line in text.splitlines():
        if line.strip().startswith("## Professional Summary"): break
        out.append(line)
    return "\n".join(out).strip()

def extract_section(text: str, heading: str) -> str:
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.strip() == heading:
            start = i + 1
            break
    if start is None: return ""
    out = []
    for line in lines[start:]:
        if line.startswith("## ") and line.strip() != heading: break
        out.append(line)
    return "\n".join(out).strip()

def parse_blocks(section_text: str):
    blocks, cur = [], None
    for raw in section_text.splitlines():
        line = raw.rstrip()
        if line.startswith("### "):
            if cur: blocks.append(cur)
            cur = {"employer": line[4:].strip(), "header": "", "bullets": []}
        elif cur and line.startswith("**") and "|" in line:
            cur["header"] = line.strip()
        elif cur and line.strip().startswith("- "):
            cur["bullets"].append(line.strip()[2:].strip())
    if cur: blocks.append(cur)
    return blocks

def enhanced_bullet_map(enhancement: dict):
    out = {}
    for key in ["promote", "keep", "compress"]:
        for item in enhancement.get(key, []) or []:
            orig = item.get("original_bullet") or item.get("bullet")
            enh = item.get("enhanced_bullet") or orig
            if orig and enh: out[orig] = enh
    return out

def safe_enhance(bullet: str, mapping: dict) -> str:
    b = mapping.get(bullet, bullet)
    b = b.replace("post-production release health checks", "post-release production health checks")
    b = b.replace("SOX support documentation", "SOX documentation")
    return re.sub(r"\s+", " ", b).strip()

def role_limit(role_code: str, employer: str, additional=False):
    rc = (role_code or "").lower()
    e = employer.lower()
    if additional: return 2
    if "federal reserve" in e or "gresham" in e:
        if "sre" in rc: return 8
        if "support" in rc: return 7
        return 7
    if "emblemhealth" in e or "aig" in e:
        return 3 if ("workday" in rc or "ba" in rc or "requirements" in rc) else 2
    if "asset control" in e or "fidelity" in e:
        return 3 if ("sre" in rc or "support" in rc) else 2
    return 1

def improve_summary(s: str) -> str:
    s = re.sub(r"\s+", " ", s).strip()
    s = s.replace("hands-on exposure to", "experience with")
    s = s.replace("positioned to ramp quickly into", "with transferable experience for")
    return s

def md_list(items):
    return "".join(f"- {x}\n" for x in items) if items else "- None identified\n"

def parse_skills(text: str):
    skills = []
    for line in extract_section(text, "## Core Skills").splitlines():
        if line.strip().startswith("- "):
            skills.append(line.strip()[2:].strip())
    return skills

def first_summary_line(text: str):
    for line in extract_section(text, "## Professional Summary").splitlines():
        if line.strip() and not line.startswith("##"):
            return line.strip()
    return ""

def assemble_v3(slug, assembled_v2, enhancement_json, outdir, run_id):
    text = assembled_v2.read_text(encoding="utf-8")
    enhancement = load_json(enhancement_json) if enhancement_json and enhancement_json.exists() else {}
    mapping = enhanced_bullet_map(enhancement)
    company = enhancement.get("company", "unknown-company")
    title = enhancement.get("title", slug)
    role_code = enhancement.get("role_code", "")

    lines = []
    lines.append(extract_contact_block(text) or f"# {company} Targeted Resume")
    lines += ["", f"<!-- Generated by Career System {run_id}; target: {company} — {title}; source: assembled-v2 + resume-enhancement -->", ""]
    lines += ["## Professional Summary", "", improve_summary(first_summary_line(text)), ""]
    lines += ["## Core Skills", "", md_list(parse_skills(text)[:12])]
    lines += ["## Professional Experience", ""]

    primary_count = 0
    exp_blocks = parse_blocks(extract_section(text, "## Professional Experience"))
    for block in exp_blocks:
        selected = [safe_enhance(b, mapping) for b in block["bullets"][:role_limit(role_code, block["employer"], False)]]
        if not selected: continue
        primary_count += len(selected)
        lines += [f"### {block['employer']}", ""]
        if block["header"]: lines += [block["header"], ""]
        lines += [f"- {b}" for b in selected]
        lines.append("")

    additional_count = 0
    add_blocks = parse_blocks(extract_section(text, "## Additional Relevant Experience"))
    add_lines = []
    for block in add_blocks:
        selected = [safe_enhance(b, mapping) for b in block["bullets"][:role_limit(role_code, block["employer"], True)]]
        if not selected: continue
        additional_count += len(selected)
        add_lines += [f"### {block['employer']}", ""]
        if block["header"]: add_lines += [block["header"], ""]
        add_lines += [f"- {b}" for b in selected]
        add_lines.append("")
    if add_lines:
        lines += ["## Additional Relevant Experience", ""]
        lines += add_lines

    lines += ["## Final Review Notes", "", "- This v0.4.9 output uses employer-aware assembly plus conservative enhanced bullet wording.", "- Review manually before importing into Teal or exporting to PDF.", "- This is not a strict two-page output yet; page compression is intentionally deferred.", ""]
    md_path = outdir / f"resume-{slug}-assembled-v3.md"
    js_path = outdir / f"resume-{slug}-assembled-v3.json"
    md_path.write_text("\n".join(lines), encoding="utf-8")
    js_path.write_text(json.dumps({"run_id": run_id, "slug": slug, "company": company, "title": title, "role_code": role_code, "source_assembled_v2": str(assembled_v2), "enhancement_file": str(enhancement_json or ""), "assembled_v3_file": str(md_path), "primary_bullets_count": primary_count, "additional_bullets_count": additional_count}, indent=2) + "\n", encoding="utf-8")
    return md_path, js_path

def main(argv):
    if len(argv) < 3:
        print("Usage: assemble_resume_narratives.py <run_id> <assembled_v2_dir> [resume_enhancement_dir]", file=sys.stderr)
        return 2
    run_id = argv[1]
    assembled_dir = Path(argv[2])
    enhancement_dir = Path(argv[3]) if len(argv) > 3 else Path("data/resume-enhancement")
    run_out = Path("ops/runs") / run_id / "output"
    data_out = Path("data/resume-versions/assembled-v3")
    run_out.mkdir(parents=True, exist_ok=True)
    data_out.mkdir(parents=True, exist_ok=True)
    generated = []
    for v2 in sorted(assembled_dir.glob("resume-*-assembled-v2.md")):
        slug = slug_from_filename(v2)
        enh = find_by_slug(enhancement_dir, "resume-enhancement-", slug, ".json")
        md, js = assemble_v3(slug, v2, enh, run_out, run_id)
        generated.append(md.name)
        for src in [md, js]:
            (data_out / src.name).write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"assembled narrative resume: {v2.name} -> {md.name}")
    report = {"run_id": run_id, "count": len(generated), "generated": generated}
    for folder in [run_out, data_out]:
        (folder / f"resume-narrative-assembly-report-{run_id}.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print("Done.")
    print(f"Run output: {run_out.resolve()}")
    print(f"Assembled v3 resumes copied to: {data_out.resolve()}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
