#!/usr/bin/env python3

import sys
from pathlib import Path


MARKER = "<!-- FRBNY_TARGETED_SECTION_INSERTED_BY_SCRIPT -->"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def extract_relevant_experience(path: Path) -> str:
    text = read(path)

    start = "### Relevant Experience"
    if start not in text:
        return text

    section = text.split(start, 1)[1].strip()

    stop_markers = [
        "## Resume Evidence Used",
        "## Interview Stories To Prepare",
        "## Insurance Portfolio",
        "## Education",
        "## Skills",
    ]

    for marker in stop_markers:
        if marker in section:
            section = section.split(marker, 1)[0].strip()

    return section.strip()


def main():
    if len(sys.argv) != 5:
        print("Usage: assemble_ats_resume.py <summary-md> <frbny-section-md> <output-md> <target-name>")
        sys.exit(1)

    summary_path = Path(sys.argv[1])
    frbny_path = Path(sys.argv[2])
    output_path = Path(sys.argv[3])
    target_name = sys.argv[4]

    contact = read(Path("data/master-profile/contact-info.md"))
    summary = read(summary_path)
    ats_history = read(Path("data/master-profile/ats-employment-history.md"))
    education = read(Path("data/master-profile/education.md"))
    publications = read(Path("data/master-profile/publications.md"))
    skills = read(Path("data/master-profile/skills.md"))

    frbny_bullets = extract_relevant_experience(frbny_path)

    if MARKER not in ats_history:
        print(f"ERROR: marker not found in ats-employment-history.md: {MARKER}")
        sys.exit(2)

    ats_history = ats_history.replace(MARKER, frbny_bullets)

    lines = [
        f"<!-- ATS Resume generated by Career System v0.7.2 target={target_name} -->",
        "",
        contact,
        "",
        "## Professional Summary",
        "",
        summary,
        "",
        "## Work Experience",
        "",
        ats_history,
        "",
        education,
        "",
        publications,
        "",
        skills,
        "",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
