#!/usr/bin/env python3

import sys
from pathlib import Path


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def extract_section(path: Path, start_marker: str = "# Resume Experience Section") -> str:
    text = read(path)
    if start_marker not in text:
        return text

    section = text.split(start_marker, 1)[1].strip()

    stop_markers = [
        "## Resume Evidence Used",
        "## Interview Stories To Prepare"
    ]

    for marker in stop_markers:
        if marker in section:
            section = section.split(marker, 1)[0].strip()

    return section


def main():
    if len(sys.argv) != 5:
        print(
            "Usage: assemble_full_resume.py "
            "<summary-md> <frbny-resume-final-md> <output-md> <target-name>"
        )
        sys.exit(1)

    summary_path = Path(sys.argv[1])
    frbny_path = Path(sys.argv[2])
    output_path = Path(sys.argv[3])
    target_name = sys.argv[4]

    contact = read(Path("data/master-profile/contact-info.md"))
    summary = read(summary_path)
    frbny_section = extract_section(frbny_path)
    older_experience = read(Path("data/master-profile/older-experience.md"))
    education = read(Path("data/master-profile/education.md"))
    publications = read(Path("data/master-profile/publications.md"))
    skills = read(Path("data/master-profile/skills.md"))

    lines = [
        f"<!-- Full Resume generated by Career System v0.7.0 target={target_name} -->",
        "",
        contact,
        "",
        "## Professional Summary",
        "",
        summary,
        "",
        "## Work Experience",
        "",
        frbny_section,
        "",
        older_experience,
        "",
        education,
        "",
        publications,
        "",
        skills,
        ""
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
