#!/usr/bin/env python3

import json
import shutil
import sys
from pathlib import Path


def copy_if_exists(src: Path, dst: Path, required: bool = False) -> bool:
    if src.exists():
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        return True

    if required:
        raise FileNotFoundError(f"Required file not found: {src}")

    return False


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: build_application_package.py <job-slug> <application-id>")
        sys.exit(1)

    job_slug = sys.argv[1].strip()
    application_id = sys.argv[2].strip()

    package_dir = Path("data/application-packages") / application_id
    package_dir.mkdir(parents=True, exist_ok=True)

    sources = {
        "resume_recommendation": Path(f"data/experience-matches/{job_slug}-resume-recommendation.json"),
        "interview_recommendation": Path(f"data/experience-matches/{job_slug}-interview-recommendation.json"),
        "generated_resume": Path(f"data/generated-resumes/{job_slug}-resume-v1.md"),
        "tailored_resume": Path(f"data/generated-resumes/{job_slug}-resume-tailored-v1.md"),
        "enhanced_resume": Path(f"data/generated-resumes/{job_slug}-resume-enhanced-v1.md"),
        "summary": Path(f"data/application-summaries/{job_slug}-summary-v1.md"),
        "full_resume": Path(f"data/full-resumes/{job_slug}-full-resume-v1.md"),
        "full_resume_html": Path(f"data/full-resumes/{job_slug}-full-resume-v1.html"),
        "ats_resume": Path(f"data/full-resumes/{job_slug}-ats-resume-v1.md"),
        "ats_resume_html": Path(f"data/full-resumes/{job_slug}-ats-resume-v1.html"),
        "ats_resume_txt": Path(f"data/ats-exports/{job_slug}-ats-resume-v1.txt"),
    }

    copied = {}

    copied["resume-recommendation.json"] = copy_if_exists(
        sources["resume_recommendation"], package_dir / "resume-recommendation.json"
    )
    copied["interview-recommendation.json"] = copy_if_exists(
        sources["interview_recommendation"], package_dir / "interview-recommendation.json"
    )
    copied["resume-generated.md"] = copy_if_exists(
        sources["generated_resume"], package_dir / "resume-generated.md"
    )
    copied["resume-tailored.md"] = copy_if_exists(
        sources["tailored_resume"], package_dir / "resume-tailored.md"
    )
    copied["resume-enhanced.md"] = copy_if_exists(
        sources["enhanced_resume"], package_dir / "resume-enhanced.md"
    )
    copied["application-summary.md"] = copy_if_exists(
        sources["summary"], package_dir / "application-summary.md"
    )
    copied["full-resume.md"] = copy_if_exists(
        sources["full_resume"], package_dir / "full-resume.md"
    )
    copied["full-resume.html"] = copy_if_exists(
        sources["full_resume_html"], package_dir / "full-resume.html"
    )
    copied["ats-resume.md"] = copy_if_exists(
        sources["ats_resume"], package_dir / "ats-resume.md"
    )
    copied["ats-resume.html"] = copy_if_exists(
        sources["ats_resume_html"], package_dir / "ats-resume.html"
    )
    copied["ats-resume.txt"] = copy_if_exists(
        sources["ats_resume_txt"], package_dir / "ats-resume.txt"
    )

    submission_notes = package_dir / "submission-notes.md"
    if not submission_notes.exists():
        write_text(
            submission_notes,
            f"""# Submission Notes

Application ID: `{application_id}`
Job Slug: `{job_slug}`

## Status

Status: Draft / Not Submitted

## Upload Artifacts

- Resume PDF: TBD
- ATS Resume TXT: ats-resume.txt
- Cover Letter: TBD

## Submission Result

Date Applied: TBD
Application URL: TBD
Confirmation: TBD

## Notes

- Application package generated by Career System v0.9.0.
""",
        )
        copied["submission-notes.md"] = True
    else:
        copied["submission-notes.md"] = True

    readme = package_dir / "README.md"
    write_text(
        readme,
        f"""# Application Package

Application ID: `{application_id}`  
Job Slug: `{job_slug}`

## Contents

- `application-summary.md`
- `resume-generated.md`
- `resume-tailored.md`
- `resume-enhanced.md`
- `full-resume.md`
- `full-resume.html`
- `ats-resume.md`
- `ats-resume.html`
- `ats-resume.txt`
- `resume-recommendation.json`
- `interview-recommendation.json`
- `submission-notes.md`
- `package-manifest.json`

## Purpose

This package collects the application-ready artifacts for one target job.

PDF files may be stored locally in this folder but are ignored by Git.
""",
    )
    copied["README.md"] = True

    manifest = {
        "application_id": application_id,
        "job_slug": job_slug,
        "package_dir": str(package_dir),
        "generator": "career-system-v0.9.0",
        "files": copied,
    }

    write_text(
        package_dir / "package-manifest.json",
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
    )

    print(f"Wrote application package: {package_dir}")


if __name__ == "__main__":
    main()
