#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

def slug_from_filename(path: Path) -> str:
    name = path.stem
    for prefix in ["resume-"]:
        if name.startswith(prefix):
            name = name[len(prefix):]
    for suffix in ["-assembled-v3", "-final", "-v1", "-v2", "-teal-v1"]:
        if name.endswith(suffix):
            name = name[:-len(suffix)]
    return name

def clean_generated_comments(text: str) -> str:
    return re.sub(r"<!--\s*Generated by Career System.*?-->\n?", "", text)

def remove_section(text: str, heading: str) -> str:
    lines = text.splitlines()
    out = []
    i = 0
    while i < len(lines):
        if lines[i].strip() == heading:
            i += 1
            while i < len(lines) and not lines[i].startswith("## "):
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)

def extract_section(text: str, heading: str) -> str:
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.strip() == heading:
            start = i + 1
            break
    if start is None:
        return ""
    out = []
    for line in lines[start:]:
        if line.startswith("## ") and line.strip() != heading:
            break
        out.append(line)
    return "\n".join(out).strip()

def replace_section(text: str, heading: str, new_body: str) -> str:
    lines = text.splitlines()
    out = []
    i = 0
    replaced = False
    while i < len(lines):
        if lines[i].strip() == heading:
            out.append(lines[i])
            out.append("")
            out.extend(new_body.strip().splitlines())
            out.append("")
            i += 1
            while i < len(lines) and not lines[i].startswith("## "):
                i += 1
            replaced = True
            continue
        out.append(lines[i])
        i += 1
    if not replaced:
        out.append("")
        out.append(heading)
        out.append("")
        out.extend(new_body.strip().splitlines())
    return "\n".join(out)

def normalize_summary(text: str) -> str:
    summary = extract_section(text, "## Professional Summary")
    lines = [x.strip() for x in summary.splitlines() if x.strip()]
    s = " ".join(lines)
    s = re.sub(r"\s+", " ", s).strip()
    s = s.replace("experience with Linux-based", "experience in Linux-based")
    s = s.replace("with experience with", "with experience in")
    s = s.replace("; with transferable experience for", ", with transferable experience for")
    s = s.replace("business-user", "business user")
    # Keep the summary as one clean paragraph. Do not invent content.
    return s

def normalize_skills(text: str, max_skills: int = 10) -> str:
    section = extract_section(text, "## Core Skills")
    skills = []
    seen = set()
    for line in section.splitlines():
        if line.strip().startswith("- "):
            skill = line.strip()[2:].strip()
            key = skill.lower()
            if skill and key not in seen:
                seen.add(key)
                skills.append(skill)
    # Prefer cleaner labels.
    replacements = {
        "Python learning / scripting ramp-up": "Python / scripting ramp-up",
        "Workday / HRIS ramp-up": "Workday / HRIS transferability",
        "GIS requirements ramp-up": "GIS requirements transferability",
        "Runbooks and support documentation": "Runbooks / support documentation",
        "Monitoring / operational health checks": "Monitoring / health checks",
        "UAT / acceptance criteria": "UAT / acceptance criteria",
    }
    skills = [replacements.get(s, s) for s in skills]
    skills = skills[:max_skills]
    return "".join(f"- {s}\n" for s in skills).rstrip()

def clean_spacing(text: str) -> str:
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() + "\n"

def remove_empty_additional_experience(text: str) -> str:
    section = extract_section(text, "## Additional Relevant Experience")
    if not section:
        return text
    has_bullets = any(line.strip().startswith("- ") for line in section.splitlines())
    if not has_bullets:
        return remove_section(text, "## Additional Relevant Experience")
    return text

def finalize_one(path: Path, output_dir: Path, run_id: str):
    slug = slug_from_filename(path)
    original = path.read_text(encoding="utf-8")

    text = clean_generated_comments(original)
    text = remove_section(text, "## Final Review Notes")
    text = remove_empty_additional_experience(text)

    summary = normalize_summary(text)
    if summary:
        text = replace_section(text, "## Professional Summary", summary)

    skills = normalize_skills(text, max_skills=10)
    if skills:
        text = replace_section(text, "## Core Skills", skills)

    text = clean_spacing(text)

    md_path = output_dir / f"resume-{slug}-final.md"
    json_path = output_dir / f"resume-{slug}-final.json"

    md_path.write_text(text, encoding="utf-8")

    data = {
        "run_id": run_id,
        "slug": slug,
        "source_file": str(path),
        "final_resume_file": str(md_path),
        "summary_present": bool(summary),
        "skills_count": len([x for x in skills.splitlines() if x.strip().startswith("- ")]),
        "removed_generated_comments": "<!-- Generated by Career System" in original,
        "removed_final_review_notes": "## Final Review Notes" in original,
    }
    json_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return md_path, json_path

def main(argv):
    if len(argv) < 3:
        print("Usage: finalize_resumes.py <run_id> <assembled_v3_dir>", file=sys.stderr)
        return 2

    run_id = argv[1]
    assembled_v3_dir = Path(argv[2])

    run_out = Path("ops/runs") / run_id / "output"
    data_out = Path("data/resume-versions/final")
    run_out.mkdir(parents=True, exist_ok=True)
    data_out.mkdir(parents=True, exist_ok=True)

    generated = []
    for src in sorted(assembled_v3_dir.glob("resume-*-assembled-v3.md")):
        md, js = finalize_one(src, run_out, run_id)
        generated.append(md.name)
        for f in [md, js]:
            (data_out / f.name).write_text(f.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"finalized resume: {src.name} -> {md.name}")

    report = {"run_id": run_id, "count": len(generated), "generated": generated}
    for folder in [run_out, data_out]:
        (folder / f"resume-finalization-report-{run_id}.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print("Done.")
    print(f"Run output: {run_out.resolve()}")
    print(f"Final resumes copied to: {data_out.resolve()}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
