#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

CANDIDATE_NAME = "Paul Lyu"
CONTACT_LINE = "Palisades Park, NJ | Business Analyst / Application Support | Resume draft generated by Career System"

BASE_EXPERIENCE = {
    "frbny": {
        "title": "Senior Business Analyst / DevOps Release Coordinator",
        "company": "Federal Reserve Bank of New York — via Gresham",
        "dates": "Apr 2017 – Feb 2026",
    },
    "aig": {
        "title": "Business Analyst / PMO / Application Support Consultant",
        "company": "AIG / Travel Guard / PMO engagements",
        "dates": "Earlier Experience",
    },
    "emblem": {
        "title": "Business Analyst / Systems Analyst",
        "company": "EmblemHealth and earlier consulting roles",
        "dates": "Earlier Experience",
    },
}

def slugify(text: str) -> str:
    text = text.lower().replace("&", "and")
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "unknown"

def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))

def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

def to_list(x: Any) -> list[str]:
    if isinstance(x, list):
        return [str(v) for v in x if str(v).strip()]
    if x:
        return [str(x)]
    return []

def md_list(items: list[str]) -> str:
    return "\n".join(f"- {x}" for x in items) if items else "- None"

def clean_skill(s: str) -> str:
    return s.strip().strip("-").strip()

def summary_for(t: dict[str, Any]) -> str:
    role_code = str(t.get("role_code") or "").lower()
    company = str(t.get("company") or "the target employer")
    role = str(t.get("role") or "the target role")
    direction = str(t.get("summary_direction") or "").strip()

    if direction:
        base = direction
    elif role_code.startswith("support"):
        base = "Senior Business Analyst and application support professional with experience in production support, release validation, runbooks, incident coordination, Linux, Oracle, and enterprise financial systems."
    elif role_code == "sre":
        base = "SRE-adjacent production support professional with experience supporting Linux-based enterprise applications, release readiness, monitoring-aware validation, incident coordination, and financial market data stability."
    elif role_code.startswith("ba") or role_code in {"bsa", "sba"}:
        base = "Senior Business Analyst / Business Systems Analyst with experience in requirements analysis, UAT, data validation, stakeholder communication, Jira stories, and enterprise modernization."
    elif role_code == "ops":
        base = "Operations and application support professional with experience in workflow analysis, data validation, operational readiness, reporting, and cross-functional execution."
    else:
        base = "Senior Business Analyst and application support professional with enterprise systems, stakeholder communication, UAT, documentation, and production-readiness experience."

    return f"{base} Tailored for {company}'s {role} role."

def core_skills(t: dict[str, Any]) -> list[str]:
    raw = to_list(t.get("keywords_to_include"))
    themes = to_list(t.get("top_resume_themes"))
    skills = []
    for x in raw + themes:
        x = clean_skill(x)
        if x and x not in skills:
            skills.append(x)
    return skills[:24]

def highlights(t: dict[str, Any]) -> list[str]:
    role_code = str(t.get("role_code") or "").lower()
    bullets = to_list(t.get("bullets_to_emphasize"))
    out = bullets[:4]

    if role_code.startswith("ba") or role_code in {"bsa", "sba"}:
        out.append("Translated business needs into requirements, user stories, acceptance criteria, validation plans, and implementation-ready documentation across enterprise technology initiatives.")
    if role_code.startswith("support"):
        out.append("Supported production readiness by coordinating issue triage, deployment validation, operational checks, and stakeholder communications.")
    if role_code == "sre":
        out.append("Applied production support discipline to Linux-based enterprise applications with emphasis on stability, incident response, health checks, and runbook-driven operations.")
    if role_code == "ops":
        out.append("Applied operational discipline to workflow execution, data quality, documentation, issue follow-up, and cross-functional coordination.")

    # De-duplicate
    dedup = []
    for b in out:
        if b not in dedup:
            dedup.append(b)
    return dedup[:6]

def frbny_bullets(t: dict[str, Any]) -> list[str]:
    role_code = str(t.get("role_code") or "").lower()
    bullets = []

    if role_code.startswith("support"):
        bullets += [
            "Supported FRBNY enterprise financial applications delivering fixed-income pricing, reference data, and streaming market data across Linux, Oracle, OpenShift, and AWS-connected environments.",
            "Coordinated production issue triage through log review, environment validation, data checks, escalation, and cross-team communication with DevOps, QA, database, infrastructure, and business stakeholders.",
            "Executed release readiness, deployment validation, post-release health checks, and operational verification for production financial applications.",
            "Maintained runbooks, deployment procedures, troubleshooting guides, validation checklists, and support documentation for operational continuity.",
        ]
    elif role_code == "sre":
        bullets += [
            "Supported Linux-based financial applications requiring production readiness, incident coordination, release validation, and operational health checks.",
            "Helped validate market data and pricing workflows where timeliness, data quality, and production stability were business critical.",
            "Coordinated troubleshooting and escalation across application, DevOps, QA, infrastructure, and operations stakeholders.",
            "Maintained runbook-driven support practices and post-release validation routines for production environments.",
        ]
    elif role_code.startswith("ba") or role_code in {"bsa", "sba"}:
        bullets += [
            "Collaborated with Product Owners and Scrum Masters to decompose epics into Jira user stories, acceptance criteria, and implementation-ready requirements.",
            "Validated REST API pricing payloads against Oracle data sources during migration from legacy on-premise services to AWS-hosted microservices.",
            "Coordinated UAT planning, test data setup, defect tracking, workflow validation, and business signoff readiness.",
            "Produced requirements, validation checklists, implementation notes, operational documentation, and stakeholder-facing support materials.",
        ]
    elif role_code == "ops":
        bullets += [
            "Supported operational readiness, validation, issue follow-up, reporting, and cross-functional execution across enterprise financial systems teams.",
            "Used structured documentation, data validation, and stakeholder communication to support production and business operations.",
            "Coordinated workflow validation and issue follow-through across technology and business stakeholders.",
            "Supported release and operational readiness through checklists, runbooks, and validation routines.",
        ]
    else:
        bullets += [
            "Supported enterprise financial systems through requirements analysis, documentation, validation, production readiness, and stakeholder communication.",
            "Coordinated cross-functional work across business, DevOps, QA, operations, and management stakeholders.",
            "Produced documentation, validation materials, and issue follow-up artifacts for enterprise system delivery and support.",
        ]

    # Add AI carefully when relevant.
    if "ai" in role_code or any("AI" in str(x) or "ai-" in str(x).lower() for x in to_list(t.get("top_resume_themes"))):
        bullets.append("Used AI-assisted workflow experiments, including Career System, to structure JD analysis, documentation, role comparison, and job-search decision support; positioned as productivity and analysis enablement, not production AI engineering.")

    return bullets[:6]

def earlier_bullets(t: dict[str, Any]) -> list[str]:
    role_code = str(t.get("role_code") or "").lower()
    if role_code.startswith("support"):
        return [
            "Supported enterprise application workflows, issue analysis, documentation, stakeholder communication, and production/business support activities.",
            "Partnered with technical and business teams to clarify requirements, validate fixes, and coordinate implementation readiness.",
        ]
    if role_code.startswith("ba") or role_code in {"bsa", "sba"}:
        return [
            "Gathered and documented business requirements, process flows, functional needs, and user-facing validation expectations.",
            "Supported UAT, defect triage, stakeholder communication, and implementation coordination across business and technology teams.",
        ]
    if role_code == "ops":
        return [
            "Supported operational reporting, process documentation, workflow coordination, and issue follow-up across business functions.",
            "Worked with stakeholders to improve clarity, execution discipline, and readiness for system/process changes.",
        ]
    return [
        "Supported business analysis, application support, documentation, UAT, and stakeholder coordination across enterprise environments.",
    ]

def claims_avoid(t: dict[str, Any]) -> list[str]:
    return to_list(t.get("claims_to_avoid")) or [
        "Review manually before applying.",
        "Do not overstate tools, platforms, or hands-on experience not supported by actual background.",
    ]

def render_experience(t: dict[str, Any]) -> str:
    fr = BASE_EXPERIENCE["frbny"]
    aig = BASE_EXPERIENCE["aig"]
    em = BASE_EXPERIENCE["emblem"]

    parts = []
    parts.append(f"### {fr['title']}\n**{fr['company']}** | {fr['dates']}\n\n{md_list(frbny_bullets(t))}")
    parts.append(f"### {aig['title']}\n**{aig['company']}** | {aig['dates']}\n\n{md_list(earlier_bullets(t))}")
    parts.append(f"### {em['title']}\n**{em['company']}** | {em['dates']}\n\n{md_list(earlier_bullets(t))}")
    return "\n\n".join(parts)

def generate_resume(t: dict[str, Any]) -> dict[str, Any]:
    company = str(t.get("company") or "Unknown")
    role = str(t.get("role") or "Unknown")
    role_code = str(t.get("role_code") or "unknown")
    family = str(t.get("recommended_resume_family") or "general BA / application-support")

    data = {
        "candidate_name": CANDIDATE_NAME,
        "contact_line": CONTACT_LINE,
        "company": company,
        "role": role,
        "role_code": role_code,
        "recommended_resume_family": family,
        "pursuit_recommendation": t.get("pursuit_recommendation", ""),
        "combined_strategy_score": t.get("combined_strategy_score", 0),
        "professional_summary": summary_for(t),
        "core_skills": core_skills(t),
        "selected_highlights": highlights(t),
        "experience_markdown": render_experience(t),
        "tailoring_notes": to_list(t.get("bullets_to_rewrite_or_add")),
        "claims_to_avoid": claims_avoid(t),
        "manual_review_required": True,
    }
    return data

def render_resume(run_id: str, r: dict[str, Any]) -> str:
    return f"""---
type: generated_resume
status: draft
run_id: {run_id}
source: career-system
candidate_name: {r['candidate_name']}
company: {r['company']}
role: {r['role']}
role_code: {r['role_code']}
recommended_resume_family: {r['recommended_resume_family']}
manual_review_required: true
---

# {r['candidate_name']}

{r['contact_line']}

## Target Role

{r['company']} — {r['role']}

## Professional Summary

{r['professional_summary']}

## Core Skills

{md_list(r['core_skills'])}

## Selected Highlights

{md_list(r['selected_highlights'])}

## Professional Experience

{r['experience_markdown']}

## Tailoring Notes

{md_list(r['tailoring_notes'])}

## Claims To Avoid / Manual Review

{md_list(r['claims_to_avoid'])}

## Manual Review Required

This is a generated first-pass resume draft. Review for truthfulness, length, formatting, and fit before applying.
"""

def render_report(run_id: str, items: list[dict[str, Any]]) -> str:
    lines = [
        "---", "type: resume_generation_report", "status: draft", f"run_id: {run_id}",
        "source: career-system", f"resume_count: {len(items)}", "---", "",
        f"# Resume Generation Report — {run_id}", "",
        "## Summary", "", f"- Generated resume drafts: **{len(items)}**",
        "- Scoring model: deterministic v0.9.0",
        "- Purpose: create first-pass Markdown resume drafts from resume-tailoring artifacts.",
        "", "## Generated Resume Index", "",
        "| Rank | Score | Company | Role | Resume Family | Role Code |",
        "|---:|---:|---|---|---|---|",
    ]
    sorted_items = sorted(items, key=lambda x: int(x.get("combined_strategy_score") or 0), reverse=True)
    for i, r in enumerate(sorted_items, 1):
        lines.append(f"| {i} | {r.get('combined_strategy_score', 0)} | {r['company']} | {r['role']} | {r['recommended_resume_family']} | {r['role_code']} |")
    lines += ["", "## How To Use This", "", "1. Start with top pursue-first roles.", "2. Review generated resume truthfulness carefully.", "3. Compress to 1–2 pages before Teal export.", "4. Use Claims To Avoid as guardrails."]
    return "\n".join(lines) + "\n"

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-id", required=True)
    ap.add_argument("--input-dir", required=True)
    ap.add_argument("--output-dir", required=True)
    args = ap.parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for path in sorted(input_dir.glob("resume-tailor-*.json")):
        if path.name.startswith("resume-tailoring-report-"):
            continue
        tailoring = load_json(path)
        resume = generate_resume(tailoring)
        generated.append(resume)
        slug = slugify(f"{resume['company']}-{resume['role_code']}-2026")
        write_json(output_dir / f"resume-generated-{slug}.json", resume)
        (output_dir / f"resume-generated-{slug}.md").write_text(render_resume(args.run_id, resume), encoding="utf-8")
        print(f"generated resume draft: {path.name} -> resume-generated-{slug}.md")

    report_base = f"resume-generation-report-{args.run_id}"
    write_json(output_dir / f"{report_base}.json", {"type": "resume_generation_report", "run_id": args.run_id, "resume_count": len(generated), "items": generated})
    (output_dir / f"{report_base}.md").write_text(render_report(args.run_id, generated), encoding="utf-8")
    print(f"generated resume generation report: {report_base}.md")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
